shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from . import views
from .views import BaseView, \
    ProductDetailViev, \
    CategoryDetailViev, \
    CartView, \
    AddToCartView, \
    DeleteFromCartView, \
    ChangeQTYView, \
    CheckoutView, \
    MakeOrderView, \
    LoginView, \
    RegistrationView

urlpatterns = [
    path('', BaseView.as_view(), name = 'base'),
    path('products/<str:ct_model>/<str:slug>/', ProductDetailViev.as_view(), name='product_detail'),
    path('category/<str:slug>/', CategoryDetailViev.as_view(), name='category_detail'),
    path('cart/', CartView.as_view(), name='cart'),
    path('add-to-cart/<str:ct_model>/<str:slug>/', AddToCartView.as_view(), name='add_to_cart'),
    path('remove-from-cart/<str:ct_model>/<str:slug>/', DeleteFromCartView.as_view(), name='delete_from_cart'),
    path('change-qty/<str:ct_model>/<str:slug>/', ChangeQTYView.as_view(), name='change_qty'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('make-order/', MakeOrderView.as_view(), name='make_order'),
    path('about-us', views.about, name='about'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(next_page="/"), name='logout'),
    path('registration/', RegistrationView.as_view(), name='registration'),

]


models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey
from django.urls import reverse
from django.utils import timezone

User = get_user_model()


def get_models_for_count(*model_names):
    return [models.Count(model_name) for model_name in model_names]


def get_product_url(obj, viewname):
    ct_model = obj.__class__._meta.model_name
    return reverse(viewname, kwargs={'ct_model': ct_model, 'slug': obj.slug})


class LatestProductsManager:

    @staticmethod
    def get_products_for_main_page(*args, **kwargs):
        with_respect_to = kwargs.get('with_respect_to')
        products = []
        ct_models = ContentType.objects.filter(model__in=args)
        for ct_model in ct_models:
            model_products = ct_model.model_class()._base_manager.all().order_by('-id')[:5]
            products.extend(model_products)
        if with_respect_to:
            ct_model = ContentType.objects.filter(model=with_respect_to)
            if ct_model.exists():
                if with_respect_to in args:
                    return sorted(
                        products, key=lambda x: x.__class__._meta.model_name.startswith(with_respect_to), reverse=True
                    )
        return products


class LatestProducts:

    objects = LatestProductsManager()


class CategoryManager(models.Manager):

    CATEGORY_NAME_COUNT_NAME = {
        'Ноутбуки': 'notebook__count',
        'Смартфоны': 'smartphone__count'
    }

    def get_queryset(self):
        return super().get_queryset()

    def get_categories_for_sidebar(self):
        models = get_models_for_count('notebook', 'smartphone')
        qs = list(self.get_queryset().annotate(*models))
        data = [
            dict(name=c.name, url=c.get_absolute_url(), count=getattr(c, self.CATEGORY_NAME_COUNT_NAME[c.name]))
            for c in qs
        ]
        return data


class Category(models.Model):

    name = models.CharField(max_length=255, verbose_name='Имя категории')
    slug = models.SlugField(unique=True)
    objects = CategoryManager()

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('category_detail', kwargs={'slug': self.slug})


class Product(models.Model):

    class Meta:
        abstract = True

    category = models.ForeignKey(Category, verbose_name='Категория', on_delete=models.CASCADE)
    title = models.CharField(max_length=255, verbose_name='Наименование')
    slug = models.SlugField(unique=True)
    image = models.ImageField(verbose_name='Изображение')
    description = models.TextField(verbose_name='Описание', null=True)
    price = models.DecimalField(max_digits=9, decimal_places=2, verbose_name='Цена')

    def __str__(self):
        return self.title

    def get_model_name(self):
        return self.__class__.__name__.lower()


class Notebook(Product):
    diagonal = models.CharField(max_length=25, verbose_name='Диагональ')
    display = models.CharField(max_length=255, verbose_name='Тип дисплея')
    processor_fleg = models.CharField(max_length=255, verbose_name='Частота процессора')
    ram = models.CharField(max_length=50, verbose_name='Оперативная память')
    video = models.CharField(max_length=255, verbose_name='Видеокарта')
    time_without_charge = models.CharField(max_length=255, verbose_name='Время заряда батареи')

    def __str__(self):
        return '{} : {}'.format(self.category.name, self.title)

    def get_absolute_url(self):
        return get_product_url(self, 'product_detail')


class Smartphone(Product):
    diagonal = models.CharField(max_length=25, verbose_name='Диагональ')
    display = models.CharField(max_length=255, verbose_name='Тип дисплея')
    resolution = models.CharField(max_length=255, verbose_name='Разрешение экрана')
    accum_volume = models.CharField(max_length=250, verbose_name='Объем батареи')
    ram = models.CharField(max_length=250, verbose_name='Оперативная память')
    sd_card = models.BooleanField(default=True, verbose_name="Наличие карты памяти")
    sd_card_volume = models.CharField(
        max_length=250, null=True, blank=True, verbose_name='Максимальный объем карты памяти')
    main_cam_mp = models.CharField(max_length=250, verbose_name='Пикселей в главной камере')
    frontal_cam_mp = models.CharField(max_length=250, verbose_name='Пикселей во фронтальной камере')

    def __str__(self):
        return '{} : {}'.format(self.category.name, self.title)

    def get_absolute_url(self):
        return get_product_url(self, 'product_detail')


class CartProduct(models.Model):

    user = models.ForeignKey('Customer', verbose_name='Покупатель', on_delete=models.CASCADE)
    cart = models.ForeignKey('Cart', verbose_name='Корзина', on_delete=models.CASCADE, related_name='related_products')
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type', 'object_id')
    qty = models.PositiveIntegerField(default=1)
    final_price = models.DecimalField(max_digits=9, decimal_places=2, verbose_name='Общая цена')

    def __str__(self):
        return "Продукт: {} (для корзины)".format(self.content_object.title)

    def save(self, *args, **kwargs):
        self.final_price = self.qty * self.content_object.price
        super().save(*args, **kwargs)


class Cart(models.Model):

    owner = models.ForeignKey('Customer', null=True, verbose_name='Владелец', on_delete=models.CASCADE)
    products = models.ManyToManyField(CartProduct, blank=True, related_name='related_cart')
    total_products = models.PositiveIntegerField(default=0)
    final_price = models.DecimalField(max_digits=9, default=0, decimal_places=2, verbose_name='Общая цена')
    in_order = models.BooleanField(default=False)
    for_anonymous_user = models.BooleanField(default=False)

    def __str__(self):
        return str(self.id)


class Customer(models.Model):

    user = models.ForeignKey(User, verbose_name='Пользователь', on_delete=models.CASCADE)
    phone = models.CharField(max_length=20, verbose_name='Номер телефона', null=True, blank=True)
    address = models.CharField(max_length=255, verbose_name='Адрес', null=True, blank=True)
    orders = models.ManyToManyField('Order', verbose_name='Заказы покупателя', related_name='related_order')

    def __str__(self):
        return "Покупатель: {} {}".format(self.user.first_name, self.user.last_name)


class Order(models.Model):

    STATUS_NEW = 'new'
    STATUS_IN_PROGRESS = 'in_progress'
    STATUS_READY = 'is_ready'
    STATUS_COMPLETED = 'completed'

    BUYING_TYPE_SELF = 'self'
    BUYING_TYPE_DELIVERY = 'delivery'

    STATUS_CHOICES = (
        (STATUS_NEW, 'Новый заказ'),
        (STATUS_IN_PROGRESS, 'Заказ в обработке'),
        (STATUS_READY, 'Заказ готов'),
        (STATUS_COMPLETED, 'Заказ выполнен')
    )

    BUYING_TYPE_CHOICES = (
        (BUYING_TYPE_SELF, 'Самовывоз'),
        (BUYING_TYPE_DELIVERY, 'Доставка')
    )

    customer = models.ForeignKey(Customer, verbose_name='Покупатель', related_name='related_orders', on_delete=models.CASCADE)
    first_name = models.CharField(max_length=255, verbose_name='Имя')
    last_name = models.CharField(max_length=255, verbose_name='Фамилия')
    phone = models.CharField(max_length=20, verbose_name='Телефон')
    cart = models.ForeignKey(Cart, verbose_name='Корзина', on_delete=models.CASCADE, null=True, blank=True)
    address = models.CharField(max_length=1024, verbose_name='Адрес', null=True, blank=True)
    status = models.CharField(
        max_length=100,
        verbose_name='Статус заказ',
        choices=STATUS_CHOICES,
        default=STATUS_NEW
    )
    buying_type = models.CharField(
        max_length=100,
        verbose_name='Тип заказа',
        choices=BUYING_TYPE_CHOICES,
        default=BUYING_TYPE_SELF
    )
    comment = models.TextField(verbose_name='Комментарий к заказу', null=True, blank=True)
    created_at = models.DateTimeField(auto_now=True, verbose_name='Дата создания заказа')
    order_date = models.DateField(verbose_name='Дата получения заказа', default=timezone.now)

    def __str__(self):
        return str(self.id)

templates/about.html
{% extends 'base.html' %}

{% block title %}
Страница про нас
{% endblock %}

{% block content %}
    <h2>Страница про нас</h2>
    <p> Добро пожаловать в наш интернет-магазин! Наша компания приветствует всех, кто зашёл на сайт!
        Наш интернет-магазин предлагает самые низкие цены, даже и не пытайтесь найти дешевле!
        Наша компания существует уже много лет, на рынке мы являемся самой надёжной и успешной компанией.
        Покупайте в нашем интернет-магазине снова и снова.
        Поверьте, у нас есть всё необходимое. Вашему вниманию самый широкий ассортимент товаров на всём рынке.
        Ждём вас за покупками каждый день, мы всегда к вашим услугам!
    </p>
{% endblock %}

templates/admin.html
{% extends 'admin/change_form.html' %}
{% load static %}

{% block admin_change_form_document_ready %}
{{ block.super }}
<script>
(function($) {
    $('#id_sd_card').on('click', function(){
        if($('#id_sd_card').prop('checked') == true){
            $('#id_sd_card_volume').prop('readonly', false)
            $('#id_sd_card_volume').val('')
            $('#id_sd_card_volume').css('background', 'white')
        }else{
            $('#id_sd_card_volume').prop('readonly', true)
            $('#id_sd_card_volume').val('')
            $('#id_sd_card_volume').css('background', 'lightgray')
        }
    })
})(django.jQuery);
</script>
{% endblock %}

templates/base.html
<!--{% load static %}-->
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Digital shop</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link type = "text/css" href="C:\Users\User\PycharmProjects\Shop\shop\mainapp\templates\styless.css" rel="stylesheet">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
              integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
              crossorigin="anonymous">
    </head>
    <style>
        body {
            padding-top:4px;
            padding-left:5px;
            padding-right:5px;
            background-image: url(https://www.tapeten.com.ua/assets/product/__imagem_SE20570.jpg)
        }

    </style>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container px-4 px-lg-15">
                <a class="navbar-brand" href="{% url 'base' %}">Digital shop</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                        <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'base' %}">Home</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'about' %}">About</a></li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button"
                               data-bs-toggle="dropdown" aria-expanded="false">Shop</a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" href="#!">All Products</a></li>
                                {% for category in categories %}
                                <li><hr class="dropdown-divider" /></li>
                                <li><a class="dropdown-item" href="{{ category.url }}">{{ category.name }} ({{ category.count }})</a></li>
                                {% endfor %}
                            </ul>
                        </li>
                    </ul>

                    <div class="collapse navbar-collapse" id="navbarResponsive"><br>
                        <ul class="navbar-nav">
                          {% if not request.user.is_authenticated %}
                          <li>
                            <a class="nav-link text-black" href="{% url 'login' %}">Авторизация</a>
                          </li>
                          <li>
                            <a class="nav-link text-black" href="{% url 'registration' %}">Регистрация</a>
                          </li>
                          {% else %}
                           <li class="nav-item">
                                  <span class="navbar-text text-black">Здравствуйте, {% if request.user.is_authenticated %}<span class="badge badge-danger"><a href="#" style="text-decoration: none; font-size: 14px;">{{ request.user.username }}</a></span>{% else %} гоcть!{% endif %}<a href="{% url 'logout' %}">| Выйти</a></span>
                           </li>
                          {% endif %}
                          </ul>
                    </div>
                    <button class="btn btn-outline-dark" type="submit">
                        <i class="bi-cart-fill me-1"></i>
                           <a href="{% url 'cart' %}">You cart</a>
                        <span class="badge bg-dark text-white ms-1 rounded-pill">{{ cart.products.count }}</span>
                    </button>
                </div>
            </div>
        </nav>
        <!-- Header-->
        <header class="bg-dark py-4">
            <div class="container px-4 px-lg-5 my-5">
                <div class="text-center text-white">
                    <h1 class="display-4 fw-bolder">Digital shop</h1>
                    <p class="lead fw-normal text-white-50 mb-0">Go digital or die</p>
                </div>
            </div>
        </header>
        <!-- Section-->
        {% block content %}
        {% if messages %}
            {% for message in messages %}
              <div class="alert alert-success alert-dismissible fade show" role="alert">
                <strong>{{ message }}</strong>
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
                    </button>
              </div>
            {% endfor %}
        {% endif %}
            <div class="container px-4 px-lg-5 mt-5">
                <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
                    {% for product in products %}
                    <div class="col mb-5">
                        <div class="card h-100">
                            <!-- Product image-->
                            <a href="{{ product.get_absolute_url }}"><img class="card-img-top" src="{{ product.image.url }}" alt=""></a>
                            <!-- Product details-->
                            <div class="card-body p-4">
                                <div class="text-center">
                                    <!-- Product name-->
                                    <h5 class="fw-bolder">
                                        <a href="{{ product.get_absolute_url }}"> {{ product.title }} </a>
                                    </h5>
                                    <!-- Product price-->
                                    <h5> {{ product.price }} </h5>
                                </div>
                            </div>
                            <!-- Product actions-->
                            <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                                <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="{% url 'add_to_cart' ct_model=product.get_model_name slug=product.slug %}">Добавить в корзину</a></div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        {% endblock content %}
        <!-- Footer-->
        <footer class="py-5 bg-dark">
            <div class="container"><p class="m-0 text-center text-white">Copyright &copy; Oleg Vostok Website 2021</p></div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>
    </body>
</html>

templates/cart.html
{% extends 'base.html' %}

{% block content %}
<h3 class="text-center mt-5 mb-5">Ваша корзина {% if not cart.products.count %}пуста{% endif %}</h3>
{% if messages %}
    {% for message in messages %}
      <div class="alert alert-success alert-dismissible fade show" role="alert">
        <strong>{{ message }}</strong>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
        </button>
      </div>
    {% endfor %}
{% endif %}
{% if cart.products.count %}
<table class="table">
  <thead>
    <tr>
      <th scope="col">Наименование</th>
      <th scope="col">Изображение</th>
      <th scope="col">Цена</th>
      <th scope="col">Количество</th>
      <th scope="col">Общая сумма</th>
      <th scope="col">Действие</th>
    </tr>
  </thead>
  <tbody>
    {% for item in cart.products.all %}
    <tr>
      <th scope="row">{{ item.content_object.title }}</th>
      <td class="w-25"><img src="{{ item.content_object.image.url }}" class="img-fluid"></td>
      <td>{{ item.content_object.price }} UAH</td>
      <td>
        <form action="{% url 'change_qty' ct_model=item.content_object.get_model_name slug=item.content_object.slug %}" method="POST">
          {% csrf_token %}
          <input type="number" class="form-control" name="qty" style="width: 78 px;" min="1" value="{{ item.qty }}">
          <br>
          <input type="submit" class="btn btn-outline-dark mt-auto" value="Изменить количество">
        </form>
      </td>
      <td>{{ item.final_price }} UAH</td>
      <td>
        <a href="{% url 'delete_from_cart' ct_model=item.content_object.get_model_name slug=item.content_object.slug %}"><button class="btn btn-outline-dark mt-auto">Удалить из корзины</button> </a>
      </td>

    </tr>

    {% endfor %}
    <tr>
      <td colspan="2"></td>
      <td><strong>Итого:</strong></td>
      <td><strong>{{ cart.total_products }}</strong></td>
      <td><strong>{{ cart.final_price }} UAH</strong></td>
      <td><a href="{% url 'checkout' %}"><button class="btn btn-outline-dark mt-auto">Перейти к оформлению</button></a></td>
    </tr>

  </tbody>

</table>
{% endif %}
{% endblock content %}

templates/category_detail.html
{% extends 'base.html' %}

{% block content %}
            <nav aria-label="breadcrumb" class="pt-3" >
              <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{% url 'base' %}">Home</a></li>
                <li class="breadcrumb-item"><a href="{{ category.url }}">{{ category.name }}</a></li>
              </ol>
            </nav>
            <div class="container px-4 px-lg-5 mt-5">
                <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
                    {% for product in category_products %}
                    <div class="col mb-5">
                        <div class="card h-100">
                            <!-- Product image-->
                            <a href="{{ product.get_absolute_url }}"><img class="card-img-top" src="{{ product.image.url }}" alt=""></a>
                            <!-- Product details-->
                            <div class="card-body p-4">
                                <div class="text-center">
                                    <!-- Product name-->
                                    <h5 class="fw-bolder">
                                        <a href="{{ product.get_absolute_url }}"> {{ product.title }} </a>
                                    </h5>
                                    <!-- Product price-->
                                    <h5> {{ product.price }} </h5>
                                </div>
                            </div>
                            <!-- Product actions-->
                            <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                                <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="{% url 'add_to_cart' ct_model=product.get_model_name slug=product.slug %}">Добавить в корзину</a></div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>

{% endblock content %}

templates/checkout.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<h3 class="text-center mt-5 mb-5">Оформление заказа</h3>
<table class="table">
  <thead>
    <tr>
      <th scope="col">Наименование</th>
      <th scope="col">Изображение</th>
      <th scope="col">Цена</th>
      <th scope="col">Количество</th>
      <th scope="col">Общая сумма</th>

    </tr>
  </thead>
  <tbody>
    {% for item in cart.products.all %}
    <tr>
      <th scope="row">{{ item.content_object.title }}</th>
      <td class="w-25"><img src="{{ item.content.object.image.url }}" class="img-fluid"></td>
      <td>{{ item.content_object.price }} UAH</td>
      <td>{{ item.qty }}</td>
      <td>{{ item.final_price }}</td>
    </tr>
    {% endfor %}

  </tbody>
</table>
<hr>
<h3 class="text-center mt-5 mb-5">Форма заказа</h3>
<form action="{% url 'make_order' %}" method="POST">
  {% csrf_token %}
  {{ form|crispy }}
  <br>
  <input type="submit" class="btn btn-outline-dark btn-block mt-auto mb-3" value="Оформить заказ">
</form>

{% endblock content %}

templates/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="row" style="margin-bottom: 200px; margin-top: 160px">
<div class="col-md-6 offset-md-3">
    <h3 class="text-center">Авторизация</h3>
    <hr>
    <form action="" method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        <hr>
        <input type="submit" class="btn btn-outline-dark mt-auto" value="Войти"> or registration on site
    </form>
</div>

</div>
{% endblock %}

templates/notebook_specification.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<table class="table">
  <tbody>
    <tr>
      <td>Диагональ</td>
      <td>{{ product.diagonal }}</td>
    </tr>
    <tr>
      <td>Тип дисплея</td>
      <td>{{ product.display }}</td>
    </tr>
    <tr>
      <td>Частота процессора</td>
      <td>{{ product.processor_fleg }}</td>
    </tr>
    <tr>
      <td>Оперативная память</td>
      <td>{{ product.ram }}</td>
    </tr>
    <tr>
      <td>Видеокарта</td>
      <td>{{ product.video }}</td>
    </tr>
    <tr>
      <td>Время заряда батареи</td>
      <td>{{ product.time_without_charge }}</td>
    </tr>
  </tbody>
</table>
</body>
</html>

templates/product_detail.html
{% extends 'base.html' %}
{% block content %}

<nav aria-label="breadcrumb" class="pt-3" >
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{% url 'base' %}">Home</a></li>
    <li class="breadcrumb-item"><a href="#">{{ product.category.name }}</a></li>
    <li class="breadcrumb-item active" aria-current="page"> {{ product.title }}</li>
  </ol>
</nav>
<div class="row" >
    <div class="col-md-4">
        <img src="{{ product.image.url }}" class="img-fluid">
    </div>
    <div class="col-md-8">
        <h3>{{ product.title }}</h3>
        <p>Цена: {{ product.price }} грн.</p>
        <p>Описание: {{ product.description }}</p>
        <hr>
        <a href="{% url 'add_to_cart' ct_model=ct_model slug=product.slug %}"><button class="btn btn-outline-dark mt-auto">Добавить в корзину</button> </a>

    </div>
    <p class="nt-4">Характеристики: </p>

    {% if product.category.slug == 'notebooks' %}
        {% include 'notebook_specification.html' %}
    {% else %}
        {% include 'smartphone_specification.html' %}
    {% endif %}
</div>







{% endblock content %}

templates/registration.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="row" style="margin-bottom: 50px; margin-top: 50px">
<div class="col-md-6 offset-md-3">
    <h3 class="text-center">Регистрация нового пользователя</h3>
    <hr>
    <form action="" method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        <hr>
        <input type="submit" class="btn btn-outline-dark mt-auto" value="Зарегистрироваться">
    </form>
</div>

</div>
{% endblock %}

templates/smartphone_specification.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<table class="table">
  <tbody>
    <tr>
      <td>Диагональ</td>
      <td>{{ product.diagonal }}</td>
    </tr>
    <tr>
      <td>Тип дисплея</td>
      <td>{{ product.display }}</td>
    </tr>
    <tr>
      <td>Разрешение экрана</td>
      <td>{{ product.resolution }}</td>
    </tr>
    <tr>
      <td>Оперативная память</td>
      <td>{{ product.ram }}</td>
    </tr>
    <tr>
      <td>Объем батареи</td>
      <td>{{ product.accum_volume }}</td>
    </tr>
    <tr>
      <td>Наличие слота для карты памяти</td>
      <td>{{ product.sd_card }}</td>
    </tr>
    <tr>
      <td>Максимальный объем карты памяти</td>
      <td>{{ product.sd_card_volume }}</td>
    </tr>
    <tr>
      <td>Пикселей в главной камере</td>
      <td>{{ product.main_cam_mp }}</td>
    </tr>
    <tr>
      <td>Пикселей во фронтальной камере</td>
      <td>{{ product.frontal_cam_mp }}</td>
    </tr>
  </tbody>
</table>
</body>
</html>